VERSION 0.6
FROM bash:4.4
WORKDIR /setup-arena


setup-templates:
	ARG service='sample'
	ARG envs='dev,prod'
	ARG docker_registry='drayfocus/earthly-sample'
	ARG version='0.1'
	COPY setup-environment.sh .
	COPY kubernetes kubernetes

	# customize kubernetes configurations
	RUN  chmod -R 775 .
	RUN mkdir -p $service/environments
	RUN ./setup-environment.sh $envs $service $docker_registry $version 

