VERSION 0.6
FROM bash:4.4
WORKDIR /setup-arena

setup-templates:
	ARG service='sample'
    ARG env='prod'
    ARG dir="./$service/environments/$env"
    ARG file="$dir/deployment.yaml"
	ARG version='0.1'
	ARG docker_registry='drayfocus/earthly-sample' 

	RUN mkdir -p $dir
	DO +DEPLOYMENT --service=$service --env=$env --dir=$dir --version=$version --docker_registry=$docker_registry
	DO +SERVICE --service=$service --env=$env --dir=$dir
	DO +NAMESPACE --service=$service --env=$env --dir=$dir
    
DEPLOYMENT:
	COMMAND
    ARG service='sample'
    ARG env='prod'
    ARG dir="./$service/environments/$env"
    ARG file="$dir/deployment.yaml"
	ARG version='0.1'
	ARG docker_registry='drayfocus/earthly-sample' 

	ARG OUTPUT="apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${service}-deployment
  namespace: ${env}-$service
  labels:
    app: $service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $service
  template:
    metadata:
      labels:
        app: $service
    spec:
      containers:
      - name: ${service}-deployment
        image: ${docker_registry}/${service}_node_app:v${version}
        ports:
        - containerPort: 3000
"
	RUN mkdir -p $dir
    RUN echo "$OUTPUT" > "$file"

SERVICE:
	COMMAND
    ARG service='sample'
    ARG env='prod'
    ARG dir="./$service/environments/$env"
    ARG file="$dir/service.yaml"
	ARG OUTPUT="apiVersion: v1
kind: Service
metadata:
  name: $service-service
  namespace: $env-$service
spec:
  selector:
    app: $service
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110
"
    RUN echo "$OUTPUT" > "$file"

NAMESPACE:
	COMMAND
    ARG service='sample'
    ARG env='prod'
    ARG dir="./$service/environments/$env"
    ARG file="$dir/namespace.yaml"

    ARG OUTPUT="apiVersion: v1
kind: Namespace
metadata:
  name: $env-$service
"
    RUN echo "$OUTPUT" > "$file"
