VERSION 0.6

LARAVELAPP:
	COMMAND
    ARG service='sample'
    ARG env='prod'
    ARG dir="./$service/environments/$env"
    ARG file="$dir/app-template.yaml"
	ARG version='0.1'
	ARG OUTPUT="apiVersion: roof.ceedcap.io/v1
kind: RoofAppTemplate
metadata:
  name: ${service}
spec:
  serviceName: ${service}
  environment: ${env}
  deploymentReplicas: 1
  imageVersion: ${version}
  configsToUse: ""
  httpsDomain1: ""
"
	RUN mkdir -p $dir
    RUN echo "$OUTPUT" > "$file"

CONFIGMAP:
	COMMAND
    ARG service='sample'
    ARG env='prod'
    ARG dir="./$service/environments/$env/extras-$service"
    ARG file="$dir/configmap.yaml"
	ARG OUTPUT="apiVersion: v1
kind: ConfigMap
metadata:
  name: ${service}
  namespace: ${env}-${service}
data:
  APP_NAME: 'SquareRoof'
  APP_ENV: 'production'
  APP_DEBUG: 'false'
"
	RUN mkdir -p $dir
    RUN echo "$OUTPUT" > "$file"

SECRETS:
	COMMAND
    ARG service='sample'
    ARG env='prod'
    ARG dir="./$service/environments/$env/extras-$service"
    ARG file="$dir/secrets.yaml"
	ARG OUTPUT="apiVersion: v1
kind: Secret
metadata:
  name: ${service}
  namespace: ${env}-${service}
type: Opaque
stringData:
  APP_KEY: ''
  DB_USERNAME: 
  DB_PASSWORD: ''
"
	RUN mkdir -p $dir
    RUN echo "$OUTPUT" > "$file"
