VERSION 0.6
FROM bash:4.4
WORKDIR /setup-arena


project:
	# clone project
	GIT CLONE https://github.com/Doctordrayfocus/VueShopifyPHP.git nodejs
	RUN rm /nodejs/package-lock.json
	SAVE ARTIFACT nodejs /nodejs

node-app:
	# We need node js to install and run the app
	FROM node:14.14.0-alpine3.12

	ARG version='0.1'
	ARG docker_registry='drayfocus/earthly-sample'
	ARG service='sample'
	ARG node_env='development'

	# First, create the application directory
	RUN mkdir -p /app

	## Then copy our app source code into the image
	COPY +project/nodejs  /app

	# Next, set our working directory
	WORKDIR /app

	## Install app packages
	RUN npm install

	## open port 3000
	EXPOSE 3000

	## Start node server

	ENV NODE_ENV ${node_env}

	IF [ "$node_env" = "development" ] 
		CMD ["npm", "run", "dev"]
	ELSE
		CMD ["npm", "run", "start"]
	END

	SAVE IMAGE --push ${docker_registry}/${service}_node_app:${version}
